-- Source tables for ontology-stack-builder (KG path)
USE DATABASE AI_READINESS_DB;
USE SCHEMA ASX200;

CREATE TABLE IF NOT EXISTS COMPANY (
  COMPANY_ID            VARCHAR(32)  NOT NULL PRIMARY KEY,
  ASX_TICKER            VARCHAR(16)  NOT NULL,
  COMPANY_NAME          VARCHAR(256) NOT NULL,
  GICS_SECTOR           VARCHAR(128),
  GICS_INDUSTRY         VARCHAR(128),
  MARKET_CAP_AUD        NUMBER(18,2),
  HQ_CITY               VARCHAR(128),
  HQ_COUNTRY            VARCHAR(8)   DEFAULT 'AU',
  EMPLOYEE_COUNT        NUMBER,
  WEBSITE_URL           VARCHAR(512),
  CAREERS_URL           VARCHAR(512),
  IR_URL                VARCHAR(512),
  BLOG_URL              VARCHAR(512),
  GOVERNANCE_URL        VARCHAR(512),
  INGESTED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_DOCUMENT (
  DOC_ID                VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  DIMENSION             VARCHAR(64)  NOT NULL,  -- governance|annual_report|hiring|engineering_blog|procurement
  SOURCE_URL            VARCHAR(1024),
  RAW_TEXT              VARCHAR(16777216),
  CONTENT_TYPE          VARCHAR(64),
  FETCH_STATUS          VARCHAR(32)  DEFAULT 'pending',  -- ok|blocked|not_found|error|pending
  FETCHED_AT            TIMESTAMP_NTZ,
  INGESTED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AI_GOVERNANCE_STATEMENT (
  STATEMENT_ID          VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  SOURCE_URL            VARCHAR(1024),
  PUBLISHED_DATE        DATE,
  POSTURE               VARCHAR(32),   -- permissive|governed|unknown
  POSTURE_RATIONALE     VARCHAR(8192),
  RISK_FRAMEWORKS       VARCHAR(2048),
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ANNUAL_REPORT (
  REPORT_ID             VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  FISCAL_YEAR           NUMBER(4),
  SOURCE_URL            VARCHAR(1024),
  AI_MENTION_COUNT      NUMBER,
  AI_STRATEGY_SUMMARY   VARCHAR(8192),
  TECH_INVESTMENT_AUD   NUMBER(18,2),
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS HIRING_SIGNAL (
  HIRING_ID             VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  SNAPSHOT_DATE         DATE,
  SOURCE_URL            VARCHAR(1024),
  TOTAL_OPEN_ROLES      NUMBER,
  ENGINEERING_ROLES     NUMBER,
  AI_ML_ROLES           NUMBER,
  DEVELOPER_DENSITY_SCORE NUMBER(5,2),
  DEVELOPER_DENSITY_TIER VARCHAR(32),  -- low|medium|high|unknown
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ENGINEERING_BLOG (
  BLOG_ID               VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  BLOG_URL              VARCHAR(1024),
  POST_DATE             DATE,
  TITLE                 VARCHAR(512),
  AI_TOPIC_TAGS         VARCHAR(2048),
  TECH_STACK            VARCHAR(2048),
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROCUREMENT_POLICY_DOC (
  DOC_ID                VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  DOC_TYPE              VARCHAR(64),
  SOURCE_URL            VARCHAR(1024),
  PUBLISHED_DATE        DATE,
  AI_VENDOR_REQUIREMENTS VARCHAR(4096),
  DATA_RESIDENCY_REQ    VARCHAR(2048),
  SUMMARY               VARCHAR(8192),
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS POLICY (
  POLICY_ID             VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  POSTURE               VARCHAR(32)  NOT NULL,  -- permissive|governed|unknown
  SUMMARY               VARCHAR(8192),
  SOURCE_STATEMENT_ID   VARCHAR(64),
  SOURCE_DOC_ID         VARCHAR(64),
  EFFECTIVE_DATE        DATE,
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BUYER (
  BUYER_ID              VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  BUYER_NAME            VARCHAR(256),
  TITLE                 VARCHAR(256),
  FUNCTION              VARCHAR(128),
  SENIORITY             VARCHAR(64),
  IS_ENTRY_POINT        BOOLEAN      DEFAULT FALSE,
  SOURCE_URL            VARCHAR(1024),
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GTM_OPPORTUNITY (
  OPPORTUNITY_ID        VARCHAR(64)  NOT NULL PRIMARY KEY,
  COMPANY_ID            VARCHAR(32)  NOT NULL,
  PLAY_TYPE             VARCHAR(128),
  PRIORITY_TIER         VARCHAR(16),  -- P1|P2|P3
  RATIONALE             VARCHAR(8192),
  RECOMMENDED_ENTRY_POINT VARCHAR(512),
  TARGET_BUYER_ID       VARCHAR(64),
  EST_DEAL_BAND         VARCHAR(64),
  EXTRACTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS COMPANY_AI_PROFILE (
  COMPANY_ID            VARCHAR(32)  NOT NULL PRIMARY KEY,
  AI_POLICY_POSTURE     VARCHAR(32),
  DEVELOPER_DENSITY_TIER VARCHAR(32),
  AI_READINESS_SCORE    NUMBER(5,2),
  CLEAR_ENTRY_POINT     VARCHAR(512),
  ENTRY_POINT_FUNCTION  VARCHAR(128),
  PROFILE_SUMMARY       VARCHAR(8192),
  UPDATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
