-- Cortex extraction: RAW_DOCUMENT -> evidence + seller tables (pilot-friendly)
-- Run after RAW_DOCUMENT is populated. Adjust MODEL if needed for your account.

USE DATABASE AI_READINESS_DB;
USE SCHEMA ASX200;

-- Stage parsed extractions (idempotent: truncate for pilot re-runs)
CREATE TABLE IF NOT EXISTS STG_DOC_EXTRACT (
  DOC_ID VARCHAR(64) PRIMARY KEY,
  COMPANY_ID VARCHAR(32),
  DIMENSION VARCHAR(64),
  EXTRACT_JSON VARIANT,
  EXTRACTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

TRUNCATE TABLE STG_DOC_EXTRACT;

INSERT INTO STG_DOC_EXTRACT (DOC_ID, COMPANY_ID, DIMENSION, EXTRACT_JSON)
SELECT
  d.DOC_ID,
  d.COMPANY_ID,
  d.DIMENSION,
  TRY_PARSE_JSON(
    REGEXP_REPLACE(
      TRIM(SNOWFLAKE.CORTEX.AI_COMPLETE(
        'mistral-large2',
        CONCAT(
          'You extract structured seller intelligence for AI readiness. Return ONLY valid JSON with no markdown fences.\n',
          'Dimension: ', d.DIMENSION, '\n',
          'Company context from document:\n',
          LEFT(d.RAW_TEXT, 12000),
          '\n\nJSON schema by dimension:\n',
          'governance: {"posture":"permissive|governed|unknown","posture_rationale":"...","risk_frameworks":"..."}\n',
          'annual_report: {"fiscal_year":2024,"ai_mention_count":0,"ai_strategy_summary":"...","tech_investment_aud":null}\n',
          'hiring: {"total_open_roles":0,"engineering_roles":0,"ai_ml_roles":0,"developer_density_tier":"low|medium|high|unknown"}\n',
          'engineering_blog: {"ai_topic_tags":"...","tech_stack":"..."}\n',
          'procurement: {"doc_type":"policy","ai_vendor_requirements":"...","data_residency_req":"...","summary":"..."}\n',
          'Also include top-level: "buyers":[...], "gtm":{...}'
        )
      )),
      '^```json\\s*|```\\s*$',
      '',
      1, 0, 'm'
    )
  )
FROM RAW_DOCUMENT d
WHERE d.FETCH_STATUS = 'ok'
  AND d.RAW_TEXT IS NOT NULL
  AND LENGTH(d.RAW_TEXT) > 300
  AND NOT EXISTS (SELECT 1 FROM STG_DOC_EXTRACT s WHERE s.DOC_ID = d.DOC_ID);

-- AI_GOVERNANCE_STATEMENT
INSERT INTO AI_GOVERNANCE_STATEMENT (
  STATEMENT_ID, COMPANY_ID, SOURCE_URL, POSTURE, POSTURE_RATIONALE, RISK_FRAMEWORKS
)
SELECT
  s.DOC_ID,
  s.COMPANY_ID,
  d.SOURCE_URL,
  COALESCE(s.EXTRACT_JSON:posture::VARCHAR, 'unknown'),
  s.EXTRACT_JSON:posture_rationale::VARCHAR,
  s.EXTRACT_JSON:risk_frameworks::VARCHAR
FROM STG_DOC_EXTRACT s
JOIN RAW_DOCUMENT d ON d.DOC_ID = s.DOC_ID
WHERE s.DIMENSION = 'governance'
  AND NOT EXISTS (SELECT 1 FROM AI_GOVERNANCE_STATEMENT g WHERE g.STATEMENT_ID = s.DOC_ID);

-- ANNUAL_REPORT
INSERT INTO ANNUAL_REPORT (
  REPORT_ID, COMPANY_ID, FISCAL_YEAR, SOURCE_URL, AI_MENTION_COUNT, AI_STRATEGY_SUMMARY, TECH_INVESTMENT_AUD
)
SELECT
  s.DOC_ID,
  s.COMPANY_ID,
  s.EXTRACT_JSON:fiscal_year::NUMBER,
  d.SOURCE_URL,
  s.EXTRACT_JSON:ai_mention_count::NUMBER,
  s.EXTRACT_JSON:ai_strategy_summary::VARCHAR,
  s.EXTRACT_JSON:tech_investment_aud::NUMBER
FROM STG_DOC_EXTRACT s
JOIN RAW_DOCUMENT d ON d.DOC_ID = s.DOC_ID
WHERE s.DIMENSION = 'annual_report'
  AND NOT EXISTS (SELECT 1 FROM ANNUAL_REPORT r WHERE r.REPORT_ID = s.DOC_ID);

-- HIRING_SIGNAL
INSERT INTO HIRING_SIGNAL (
  HIRING_ID, COMPANY_ID, SNAPSHOT_DATE, SOURCE_URL,
  TOTAL_OPEN_ROLES, ENGINEERING_ROLES, AI_ML_ROLES, DEVELOPER_DENSITY_TIER
)
SELECT
  s.DOC_ID,
  s.COMPANY_ID,
  CURRENT_DATE(),
  d.SOURCE_URL,
  s.EXTRACT_JSON:total_open_roles::NUMBER,
  s.EXTRACT_JSON:engineering_roles::NUMBER,
  s.EXTRACT_JSON:ai_ml_roles::NUMBER,
  COALESCE(s.EXTRACT_JSON:developer_density_tier::VARCHAR, 'unknown')
FROM STG_DOC_EXTRACT s
JOIN RAW_DOCUMENT d ON d.DOC_ID = s.DOC_ID
WHERE s.DIMENSION = 'hiring'
  AND NOT EXISTS (SELECT 1 FROM HIRING_SIGNAL h WHERE h.HIRING_ID = s.DOC_ID);

-- ENGINEERING_BLOG
INSERT INTO ENGINEERING_BLOG (BLOG_ID, COMPANY_ID, BLOG_URL, AI_TOPIC_TAGS, TECH_STACK)
SELECT
  s.DOC_ID,
  s.COMPANY_ID,
  d.SOURCE_URL,
  s.EXTRACT_JSON:ai_topic_tags::VARCHAR,
  s.EXTRACT_JSON:tech_stack::VARCHAR
FROM STG_DOC_EXTRACT s
JOIN RAW_DOCUMENT d ON d.DOC_ID = s.DOC_ID
WHERE s.DIMENSION = 'engineering_blog'
  AND NOT EXISTS (SELECT 1 FROM ENGINEERING_BLOG b WHERE b.BLOG_ID = s.DOC_ID);

-- PROCUREMENT_POLICY_DOC
INSERT INTO PROCUREMENT_POLICY_DOC (
  DOC_ID, COMPANY_ID, DOC_TYPE, SOURCE_URL, AI_VENDOR_REQUIREMENTS, DATA_RESIDENCY_REQ, SUMMARY
)
SELECT
  s.DOC_ID,
  s.COMPANY_ID,
  COALESCE(s.EXTRACT_JSON:doc_type::VARCHAR, 'policy'),
  d.SOURCE_URL,
  s.EXTRACT_JSON:ai_vendor_requirements::VARCHAR,
  s.EXTRACT_JSON:data_residency_req::VARCHAR,
  s.EXTRACT_JSON:summary::VARCHAR
FROM STG_DOC_EXTRACT s
JOIN RAW_DOCUMENT d ON d.DOC_ID = s.DOC_ID
WHERE s.DIMENSION = 'procurement'
  AND NOT EXISTS (SELECT 1 FROM PROCUREMENT_POLICY_DOC p WHERE p.DOC_ID = s.DOC_ID);

-- POLICY (rollup from governance + procurement)
INSERT INTO POLICY (POLICY_ID, COMPANY_ID, POSTURE, SUMMARY, SOURCE_STATEMENT_ID, SOURCE_DOC_ID)
SELECT
  'pol_' || s.COMPANY_ID,
  s.COMPANY_ID,
  COALESCE(s.EXTRACT_JSON:posture::VARCHAR, 'unknown'),
  COALESCE(s.EXTRACT_JSON:posture_rationale::VARCHAR, s.EXTRACT_JSON:summary::VARCHAR),
  CASE WHEN s.DIMENSION = 'governance' THEN s.DOC_ID END,
  CASE WHEN s.DIMENSION = 'procurement' THEN s.DOC_ID END
FROM STG_DOC_EXTRACT s
WHERE s.DIMENSION IN ('governance', 'procurement')
  AND NOT EXISTS (SELECT 1 FROM POLICY p WHERE p.POLICY_ID = 'pol_' || s.COMPANY_ID);

-- BUYER (from any dimension with buyers array)
INSERT INTO BUYER (BUYER_ID, COMPANY_ID, BUYER_NAME, TITLE, FUNCTION, SENIORITY, IS_ENTRY_POINT, SOURCE_URL)
SELECT
  'buy_' || s.COMPANY_ID || '_' || f.index,
  s.COMPANY_ID,
  f.value:name::VARCHAR,
  f.value:title::VARCHAR,
  f.value:function::VARCHAR,
  f.value:seniority::VARCHAR,
  COALESCE(f.value:is_entry_point::BOOLEAN, FALSE),
  d.SOURCE_URL
FROM STG_DOC_EXTRACT s
JOIN RAW_DOCUMENT d ON d.DOC_ID = s.DOC_ID,
LATERAL FLATTEN(input => s.EXTRACT_JSON:buyers) f
WHERE NOT EXISTS (
  SELECT 1 FROM BUYER b WHERE b.BUYER_ID = 'buy_' || s.COMPANY_ID || '_' || f.index
);

-- GTM_OPPORTUNITY
INSERT INTO GTM_OPPORTUNITY (
  OPPORTUNITY_ID, COMPANY_ID, PLAY_TYPE, PRIORITY_TIER, RATIONALE, RECOMMENDED_ENTRY_POINT
)
SELECT
  'gtm_' || s.COMPANY_ID,
  s.COMPANY_ID,
  s.EXTRACT_JSON:gtm:play_type::VARCHAR,
  COALESCE(s.EXTRACT_JSON:gtm:priority_tier::VARCHAR, 'P2'),
  s.EXTRACT_JSON:gtm:rationale::VARCHAR,
  s.EXTRACT_JSON:gtm:recommended_entry_point::VARCHAR
FROM STG_DOC_EXTRACT s
WHERE s.EXTRACT_JSON:gtm IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM GTM_OPPORTUNITY g WHERE g.OPPORTUNITY_ID = 'gtm_' || s.COMPANY_ID);

-- COMPANY_AI_PROFILE
MERGE INTO COMPANY_AI_PROFILE t
USING (
  SELECT
    c.COMPANY_ID,
    MAX(p.POSTURE) AS AI_POLICY_POSTURE,
    MAX(h.DEVELOPER_DENSITY_TIER) AS DEVELOPER_DENSITY_TIER,
    MAX(g.RECOMMENDED_ENTRY_POINT) AS CLEAR_ENTRY_POINT,
    MAX(b.FUNCTION) AS ENTRY_POINT_FUNCTION
  FROM COMPANY c
  LEFT JOIN POLICY p ON p.COMPANY_ID = c.COMPANY_ID
  LEFT JOIN HIRING_SIGNAL h ON h.COMPANY_ID = c.COMPANY_ID
  LEFT JOIN GTM_OPPORTUNITY g ON g.COMPANY_ID = c.COMPANY_ID
  LEFT JOIN BUYER b ON b.COMPANY_ID = c.COMPANY_ID AND b.IS_ENTRY_POINT
  GROUP BY c.COMPANY_ID
) s
ON t.COMPANY_ID = s.COMPANY_ID
WHEN MATCHED THEN UPDATE SET
  AI_POLICY_POSTURE = s.AI_POLICY_POSTURE,
  DEVELOPER_DENSITY_TIER = s.DEVELOPER_DENSITY_TIER,
  CLEAR_ENTRY_POINT = s.CLEAR_ENTRY_POINT,
  ENTRY_POINT_FUNCTION = s.ENTRY_POINT_FUNCTION,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  COMPANY_ID, AI_POLICY_POSTURE, DEVELOPER_DENSITY_TIER, CLEAR_ENTRY_POINT, ENTRY_POINT_FUNCTION
) VALUES (
  s.COMPANY_ID, s.AI_POLICY_POSTURE, s.DEVELOPER_DENSITY_TIER, s.CLEAR_ENTRY_POINT, s.ENTRY_POINT_FUNCTION
);
